
const NAMESPACE = 'containers/employees/';

export const GET_EMPLOYEES = `${NAMESPACE}GET_EMPLOYEES`;
export const GET_EMPLOYEES_SUCCESS = `${NAMESPACE}GET_EMPLOYEES_SUCCESS`;
export const GET_EMPLOYEES_FAILURE = `${NAMESPACE}GET_EMPLOYEES_FAILURE`;


export const VIEW_EMPLOYEE = `${NAMESPACE}VIEW_EMPLOYEE`;
export const VIEW_EMPLOYEE_SUCCESS = `${NAMESPACE}VIEW_EMPLOYEE_SUCCESS`;
export const VIEW_EMPLOYEE_FAILURE = `${NAMESPACE}VIEW_EMPLOYEE_FAILURE`;

export const ADD_EMPLOYEE = `${NAMESPACE}ADD_EMPLOYEE`;
export const ADD_EMPLOYEE_SUCCESS = `${NAMESPACE}ADD_EMPLOYEE_SUCCESS`;
export const ADD_EMPLOYEE_FAILURE = `${NAMESPACE}ADD_EMPLOYEE_FAILURE`;


export const UPDATE_EMPLOYEE = `${NAMESPACE}UPDATE_EMPLOYEE`;
export const UPDATE_EMPLOYEE_SUCCESS = `${NAMESPACE}UPDATE_EMPLOYEE_SUCCESS`;
export const UPDATE_EMPLOYEE_FAILURE = `${NAMESPACE}UPDATE_EMPLOYEE_FAILURE`;

export const DELETE_EMPLOYEE = `${NAMESPACE}DELETE_EMPLOYEE`;
export const DELETE_EMPLOYEE_SUCCESS = `${NAMESPACE}DELETE_EMPLOYEE_SUCCESS`;
export const DELETE_EMPLOYEE_FAILURE = `${NAMESPACE}DELETE_EMPLOYEE_FAILURE`;

export const RESET_LOADING_STATE = `${NAMESPACE}RESET_LOADING_STATE`;